#!/usr/bin/env bash

system_update() {
    echo "updating system"
    sudo apt update
    sudo apt -y dist-upgrade
}

remove_apps() {
    echo "removing libreoffice and geary"
    sudo apt purge -y libreoffice\*
    sudo apt purge -y geary
}

install_apt_packages() {
    echo "installing deb packages"
    APPS="fish fzf thunderbird nextcloud-desktop flameshot code timeshift python-is-python3 steam discord neovim picom nitrogen nemo"
    sudo apt install -y $APPS
}

configure_default_apps() {
    echo "configuring nemo"
    xdg-mime default nemo.desktop inode/directory application/x-gnome-saved-search
    gsettings set org.gnome.shell.extensions.ding use-nemo true
    gsettings set org.gnome.shell.extensions.ding show-home true
}

install_pacstall() {
    echo "installing pacstall"
    printf '%s/n' y | sudo bash -c "$(curl -fsSL https://git.io/JsADh || wget -q https://git.io/JsADh -O -)"
}

install_pacstall_packages() {
    echo "installing packages with pacstall"
    APPS="btop-bin veracrypt-deb nala-deb starship-bin"
    pacstall -Ip $APPS

}

install_enpass() {
    echo "installing enpass"
    sudo echo "deb https://apt.enpass.io/ stable main" | sudo tee -a /etc/apt/sources.list.d/enpass.list
    wget -O - https://apt.enpass.io/keys/enpass-linux.key | tee /etc/apt/trusted.gpg.d/enpass.asc
    sudo apt install update
    sudo apt install enpass -y
}

install_wez_term() {
    echo "installing wezterm"
    curl -LO https://github.com/wez/wezterm/releases/download/20221119-145034-49b9839f/wezterm-20221119-145034-49b9839f.Ubuntu22.04.deb
    sudo apt install -y ./wezterm-20221119-145034-49b9839f.Ubuntu22.04.deb
}

install_asdf() {
    echo "installing asdf"
    git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.10.0 >>/dev/null
    . $HOME/.asdf/asdf.sh
    install_asdf_python
    install_asdf_go
    install_asdf_nodejs
}

install_asdf_python() {
    BUILD_DEPS="build-essential libsqlite3-dev sqlite3 bzip2 libbz2-dev zlib1g-dev libssl-dev openssl libgdbm-dev libgdbm-compat-dev liblzma-dev libreadline-dev libncursesw5-dev libffi-dev uuid-dev"
    sudo apt install -y $BUILD_DEPS
    asdf plugin add python
    asdf install python latest
    asdf global python latest
}

install_python_tools() {
    sudo apt install -y pipx
    pipx ensurepath
    pipx install pdm
    pipx install pre-commit
    pipx install black
}

install_asdf_go() {
    sudo apt install -y coreutils
    asdf plugin-add golang https://github.com/kennyp/asdf-golang.git
    asdf install golang latest
    asdf global golang latest
}

install_asdf_nodejs() {
    asdf install nodejs lts
    asdf global nodejs lts
}

install_rustup() {
    echo "installing rustup"
    sudo apt install -y cmake
    curl https://sh.rustup.rs -sSf | sh -s -- -y
}

install_regolith() {
    echo "installing regolith"
    wget -qO - https://regolith-desktop.org/regolith.key |
        gpg --dearmor | sudo tee /usr/share/keyrings/regolith-archive-keyring.gpg >/dev/null

    echo deb "[arch=amd64 signed-by=/usr/share/keyrings/regolith-archive-keyring.gpg] \
    https://regolith-desktop.org/release-ubuntu-jammy-amd64 jammy main" |
        sudo tee /etc/apt/sources.list.d/regolith.list

    sudo apt update
    sudo apt install regolith-desktop

    i3BAR="i3xrocks-bluetooth i3xrocks-cpu-usage i3xrocks-focused-window-name i3xrocks-media-player i3xrocks-memory i3xrocks-microphone i3xrocks-net-traffic i3xrocks-rofication i3xrocks-time i3xrocks-volume regolith-i3xrocks-config"
    sudo apt install -y $i3BAR

    sudo apt install -y regolith-compositor-picom-glx

    i3CONFIGS="regolith-i3-base-launchers regolith-i3-default-style regolith-i3-navigation regolith-i3-networkmanager regolith-i3-next-workspace regolith-i3-resize regolith-i3-session regolith-i3-unclutter regolith-i3-user-programs regolith-i3-workspace-config"

    sudo apt remove -y $i3CONFIGS

}

install_apps() {
    install_apt_packages
    install_pacstall
    # install_enpass
}

cleanup() {
    sudo apt autoremove -y
}

main() {
    process_flags "$@"
    while [[ $1 = -* ]]; do shift; done

    if ((${#@} == 0)); then
        remove_apps
        system_update
        install_apps
        install_rustup
        install_asdf
        install_python_tools
        configure_default_apps
        install_wez_term
        install_regolith
        cleanup
    else
        for cmd in "$@"; do
            "$cmd"
        done
    fi
}

main "$@"
