#!/usr/bin/env bash
# TODO: separate out functions
# add trezor-app
# add unity3d-app

system_update() {
    echo "updating system"
    sudo apt update
    sudo apt -y dist-upgrade
}

setup_acpi_wakeup_fix() {
    sudo cp $HOME/Utils/system-scripts/disable-devices-as-wakeup.service /etc/systemd/system/
    sudo systemctl enable disable-devices-as-wakeup.service
    sudo systemctl start disable-devices-as-wakeup.service
}

remove_apps() {
    echo "removing libreoffice and geary"
    sudo apt purge -y libreoffice\*
    sudo apt purge -y geary
}

install_apt_packages() {
    echo "installing deb packages"
    sudo apt install -y thunderbird \
        nextcloud-desktop \
        code \
        timeshift \
        python-is-python3 \
        steam \
        discord \
        nemo \
        ripgrep \
        exa
}

configure_default_apps() {
    echo "configuring nemo"
    xdg-mime default nemo.desktop inode/directory application/x-gnome-saved-search
    gsettings set org.gnome.shell.extensions.ding use-nemo true
    gsettings set org.gnome.shell.extensions.ding show-home true
}

install_pacstall() {
    echo "installing pacstall"
    printf '%s/n' y | sudo bash -c "$(curl -fsSL https://git.io/JsADh || wget -q https://git.io/JsADh -O -)"
}

install_pacstall_packages() {
    echo "installing packages with pacstall"
    pacstall -IP veracrypt-deb
    # nala-deb
}

# install_flatpak_packages() {
#     flatpak install flathub com.mattjakeman.ExtensionManager
# }

install_enpass() {
    echo "installing enpass"
    pacstall -IP enpass-bin
}

install_terminal_tools() {
    echo "installing alacritty"
    pacstall -IP alacritty
    sudo update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator /usr/bin/alacritty 20
    sudo update-alternatives --config x-terminal-emulator

    echo "installing starship prompt"
    pacstall -IP starship-bin

    echo "installing fish"
    sudo apt install -y fish

    mkdir -p ~/.local/bin
    echo "installing bat"
    sudo apt install -y bat
    ln -s /usr/bin/batcat ~/.local/bin/bat

    echo "installing fd"
    sudo apt install -y fd-find
    ln -s $(which fdfind) ~/.local/bin/fd

    echo "installing zoxide"
    sudo apt install -y zoxide

    echo "installing lvim"
    LV_BRANCH='release-1.2/neovim-0.8' bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/fc6873809934917b470bff1b072171879899a36b/utils/installer/install.sh)
}

install_cargo() {
    echo "installing cargo crates"
    sudo apt install -y libdbus-1-dev libncursesw5-dev libpulse-dev libssl-dev libxcb1-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev
    cargo install sccache
    cargo install ncspot \
        zellij \
        wiki-tui \
        gitui \
        rtx-cli \
        du-dust \
        skim \
        cargo-update
}

setup_rtx() {
    echo "configuring rtx"
    rtx activate
    rtx install
}

install_python_tools() {
    sudo nala install -y pipx
    pipx ensurepath
    pipx install pre-commit
    pipx install black
    pipx install qmk
    pipx install ruff
}

install_rustup() {
    echo "installing rustup"
    sudo nala install -y cmake
    curl https://sh.rustup.rs -sSf | sh -s -- -y
}

# setup_pop_shell() {
#     echo "setting pop shell keybindings"
#     sudo chmod +x $HOME/.config/yadm/pop_os_shortcuts.sh
#     $HOME/.config/yadm/pop_os_shortcuts.sh
# }

install_fonts() {
    echo "installing nerd-fonts"
    sudo chmod +x $HOME/.config/yadm/install_fonts.sh
    $HOME/.config/yadm/install_fonts.sh
}

install_regolith() {
    echo "installing regolith"
    wget -qO - https://regolith-desktop.org/regolith.key |
        gpg --dearmor | sudo tee /usr/share/keyrings/regolith-archive-keyring.gpg >/dev/null
    echo deb "[arch=amd64 signed-by=/usr/share/keyrings/regolith-archive-keyring.gpg] \
    https://regolith-desktop.org/release-ubuntu-jammy-amd64 jammy main" |
        sudo tee /etc/apt/sources.list.d/regolith.list

    sudo apt update
    sudo apt install regolith-desktop
    sudo apt install -y i3xrocks-bluetooth \
        i3xrocks-cpu-usage \
        i3xrocks-focused-window-name \
        i3xrocks-media-player \
        i3xrocks-memory \
        i3xrocks-microphone \
        i3xrocks-net-traffic \
        i3xrocks-rofication \
        i3xrocks-time \
        i3xrocks-volume \
        regolith-i3xrocks-config

    sudo apt install -y regolith-compositor-picom-glx

    sudo apt install -y regolith-look-blackhole \
        regolith-look-ayu-dark

    # sudo apt remove -y regolith-i3-base-launchers \
    #     regolith-i3-default-style \
    #     regolith-i3-navigation \
    #     regolith-i3-networkmanager \
    #     regolith-i3-next-workspace \
    #     regolith-i3-resize \
    #     regolith-i3-session \
    #     regolith-i3-unclutter \
    #     regolith-i3-user-programs \
    #     regolith-i3-workspace-config
}

install_apps() {
    # install_pacstall
    install_pacstall_packages
    install_apt_packages
    # install_flatpak_packages
    install_cargo
    install_enpass
}

cleanup() {
    sudo apt autoremove -y
}

main() {
    remove_apps
    system_update
    install_rustup
    install_apps
    setup_rtx
    install_python_tools
    install_terminal_tools
    # setup_pop_shell
    install_fonts
    configure_default_apps
    install_regolith
    cleanup
}

main
