[auto-move-windows]
application-list=['discord.desktop:9', 'thunderbird.desktop:10', 'steam.desktop:8']

[dash-to-dock]
click-action='minimize-or-previews'
dash-max-icon-size=36
dock-fixed=false
intellihide=true
manualhide=false

[ding]
add-volumes-opposite=false
show-drop-place=false
show-home=false
show-link-emblem=false
use-nemo=true

[horizontal-workspace-indicator]
icons-style='lines'
widget-orientation='horizontal'
widget-position='left'

[mediacontrols]
extension-position='right'
mouse-actions=['toggle_play', 'toggle_menu', 'none', 'none', 'none', 'none', 'none', 'none']
seperator-chars=['|', '|']
show-seek-back=false
show-seek-forward=false
show-sources-menu=false
track-label=['track', '-', 'artist']

[noannoyance]
by-class=['Microsoft Teams - Preview', 'Firefox']
enable-ignorelist=true

[openweather]
position-in-panel='right'
position-index=15
prefs-default-height=704
prefs-default-width=1280
use-system-icons=true

[pop-cosmic]
clock-alignment='RIGHT'
show-applications-button=false
show-workspaces-button=false

[pop-shell]
active-hint-border-radius=uint32 0
gap-inner=uint32 0
gap-outer=uint32 0
show-title=false
tile-by-default=true

[space-bar/behavior]
scroll-wheel='panel'
show-empty-workspaces=false
smart-workspace-names=true

[space-bar/shortcuts]
enable-activate-workspace-shortcuts=false
